local func = require "entry/func"
local coor = require "entry/coor"
local pipe = require "entry/pipe"
local general = require "entry/general"
local mus = require "mus_track"
local quat = require "entry/quaternion"
local dump = require "luadump"

local unpack = table.unpack
local ma = math
local pi = ma.pi

local trackWidth = 5

local function makeSize(left, right)
    return {
        lb = coor.xyz(left, -2.5, 0),
        lt = coor.xyz(left, 2.5, 0),
        rt = coor.xyz(right, 2.5, 0),
        rb = coor.xyz(right, -2.5, 0)
    }
end

function data()
    return {
        availability = {
            yearFrom = 0,
            yearTo = 0,
        },
        buildMode = "SINGLE",
        cost = {
            price = 15000,
        },
        description = {
            name = _("Underground station track"),
            description = _("An underground station track"),
            icon = "ui/construction/street/underpass_entry.tga"
        },
        category = {
            categories = {"platform"},
        },
        type = "mus_platform",
        order = {
            value = 260,
        },
        metadata = {
            platform = true,
            width = 5
        },
        
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            local allArcs = mus.trackArcs(trackWidth)(result.config, result.arcs[slotId])
            local refArc = pipe.new * allArcs[1]()()() * pipe.map(mus.arc2Edges) * pipe.flatten() * pipe.map(pipe.map(coor.vec2Tuple))
            local edges = {
                type = "TRACK",
                alignTerrain = false,
                params = {
                    type = "high_speed.lua",
                    catenary = true,
                },
                edgeType = "TUNNEL",
                edgeTypeName = "ust_void.lua",
                edges = refArc,
                snapNodes = {5, 11},
                tag2nodes = {},
            }
            
            local newModels = mus.trackModels(result.config, allArcs, mus.fitModel)
            
            result.models =
                pipe.new
                * result.models
                + newModels
            
            result.edgeLists = pipe.new
                * result.edgeLists
                / edges
        end,
        
        getModelsFn = function(params)
            local hW = 5
            local vectorW = func.interlace({
                -hW
                - hW + edgeWidth,
                -hW + edgeWidth + sideWidth,
                hW - edgeWidth - sideWidth,
                hW - edgeWidth,
                hW
            })
            local vectorMW = {edgeWidth, sideWidth, (hW - edgeWidth - sideWidth) * 2, sideWidth, edgeWidth}
            local vectorM = {"edgeLeft", "left", "central", "right", "edgeRight"}
            
            return
                pipe.new
                * pipe.mapn(vectorW, vectorMW, vectorM)(function(w, mw, m)
                    local size = makeSize(unpack(w))
                    return {
                        general.newModel(m .. "_tl.mdl", mus.fitModel(mw, segmentLength, platformHeight, size, true, true)),
                        general.newModel(m .. "_br.mdl", mus.fitModel(mw, segmentLength, platformHeight, size, false, false))
                    }
                end)
                * pipe.flatten()
        end
    }

end
