local func = require "entry/func"
local coor = require "entry/coor"
local pipe = require "entry/pipe"
local general = require "entry/general"
local mus = require "mus_platform"
local quat = require "entry/quaternion"
local dump = require "luadump"

local unpack = table.unpack
local ma = math
local pi = ma.pi

local platformWidth = 10
local stairsWidth = 7

local platformArcs = mus.platformArcs(platformWidth, stairsWidth)

function data()
    return {
        availability = {
            yearFrom = 0,
            yearTo = 0,
        },
        buildMode = "SINGLE",
        cost = {
            price = 15000,
        },
        description = {
            name = _("10m Underground platform"),
            description = _("An underground platform of 10m wide"),
            icon = "ui/construction/street/underpass_entry.tga"
        },
        category = {
            categories = {"platform"},
        },
        type = "mus_platform",
        order = {
            value = 260,
        },
        metadata = {
            platform = true,
            width = 10
        },
        
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            local rank = result.slotId2Rank[slotId]
            local allArcs = platformArcs(result.config, result.arcs[rank])
            local newModels = mus.platformModels(result.config, allArcs, mus.fitModel)
            
            
            local refArc = pipe.new
                * {allArcs[3]()()(-2.5), allArcs[3]()()(2.5)}
                * pipe.map(pipe.map(mus.arc2Edges))
                * pipe.flatten()
                * pipe.flatten()
                * pipe.map(pipe.map(coor.vec2Tuple))
            
            local edges = {
                type = "TRACK",
                alignTerrain = false,
                params = {
                    type = "uus_mock.lua",
                    catenary = true,
                },
                edgeType = "TUNNEL",
                edgeTypeName = "ust_void.lua",
                edges = refArc,
                snapNodes = {},
                tag2nodes = {},
            }
            
            local leftTerminals, rightTerminals, linkings, terminalCounts = mus.generateTerminals(allArcs)
            
            result.models =
                pipe.new
                * result.models
                + 
                (newModels
                + linkings) * pipe.map(function(m) return func.with(m, { tag = "__module_" .. slotId }) end)
            
            result.terminalInfo[rank] = {
                {#result.models, #result.models + terminalCounts - 1},
                {#result.models + terminalCounts, #result.models + terminalCounts + terminalCounts - 1},
            }
            
            result.models = result.models + leftTerminals + rightTerminals
            
            result.edgeLists = pipe.new
                * result.edgeLists
                / edges
        end,
        
        getModelsFn = function(params)
            return {}
        end
    }

end
