local func = require "entry/func"
local coor = require "entry/coor"
local pipe = require "entry/pipe"
local general = require "entry/general"
local mus = require "mus_platform"
local quat = require "entry/quaternion"
local dump = require "luadump"

local unpack = table.unpack

local mType = "mus_downstairs"
function data()
    return {
        availability = {
            yearFrom = 0,
            yearTo = 0,
        },
        buildMode = "SINGLE",
        cost = {
            price = 15000,
        },
        description = {
            name = _("10m Underground platform"),
            description = _("An underground platform of 10m wide"),
            icon = "ui/construction/street/underpass_entry.tga"
        },
        category = {
            categories = {"Stairs"},
        },
        type = mType,
        order = {
            value = 260,
        },
        metadata = {
            platform = true,
            width = 10,
            type = mType
        },
        
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            local pos = slotId % 1000
            local refPos = (slotId - slotId % 100000) / 100000
            local refSlot = result.pos2SlotId[refPos]
            local rank = result.slotId2Rank[refSlot]
             
            local allArcs = result.allArcs[rank]
            local newModels = mus.downstairsModels(result.config, allArcs, mus.fitModel, pos)

            local blocks = allArcs.blockCoords.platform.lane.mc
            local pt1 = (blocks[pos - 1].i):avg(blocks[pos - 1].s)
            local pt2 = blocks[pos].s
            local pt3 = blocks[pos].i - coor.xyz(0, 0, 3)
            local lane =
                {
                    general.newModel("mus/person_lane.mdl", general.mRot(pt2 - pt1), coor.trans(pt1)),
                    general.newModel("mus/person_lane.mdl", general.mRot(pt3 - pt2), coor.trans(pt2))
                }
            
            newModels = newModels + lane
            
            result.invoke[#result.invoke + 1] = function()
                result.models = result.models * pipe.filter(function(m) return m.tag ~= "__module_" .. refSlot or m.pos ~= pos end) + general.withTag(tag)(newModels)
            end
        end,
        
        getModelsFn = function(params)
            return {}
        end
    }

end
