local mus = require "mus"
function data()
    return {
        createTemplateFn = mus.createTemplateFn,
        updateFn = mus.updateFn,
        upgradeFn = mus.upgradeFn,
        preProcessFn = function(modules, change)
            if change.added then
                modules[change.slotId] = change.module
            else
                modules[change.slotId] = nil
            end
            return modules
        end
    }
end
