local descEN = [[
]]

local descDE = [[]]

local descCN = [[]]

function data()
    return {
        en = {
            ["name"] = "Ultimate Underground Station",
            ["desc"] = descEN,
        },
        de = {
            ["name"] = "Ultimate Underground Station",
            ["desc"] = descDE,
            ["Number of tracks"] = "Anzahl an Gleisen",
            ["Transit Tracks"] = "Durchfahrtsgleise",
            ["Position"] = "Position",
            ["Left"] = "Links",
            ["Centre"] = "Zentrum",
            ["Sides"] = "Seiten",
            ["Right"] = "Rechts",
            ["Radius"] = "Radius",
            ["Platform"] = "Bahnsteig",
            ["Length"] = "Länge",
            ["Outter"] = "Außen",
            ["Polarity"] = "Richtung",
            ["Platform Variation"] = "Bahnsteig Variation",
            ["Narrowest Extremity Width"] = "Schmälste Breite",
            ["Uniform"] = "Einheitlich",
            ["Linear"] = "Linear",
            ["Quadratic"] = "Quadratisch",
            ["Quartic"] = "Bi-Quadratisch",
            ["Gauusian"] = "Gaußsche",
            ["Gauusian 2"] = "Gaußsche 2",
            ["Shortest Platform"] = "Kürzester Bahnsteig",
            ["Offset Platform Max."] = "Maximaler Bahnsteigversatz",
            ["Track"] = "Schiene",
            ["Reference"] = "Referenz",
            ["Center"] = "Zentrum",
            ["Unaffected platforms"] = "Unbeinfluuste Bahnsteige",
            ["Main Entry"] = "Haupteingang",
            ["None"] = "Keiner",
            ["Central"] = "Zentral",
            ["Both"] = "Beide",
            ["Entry"] = "Eingang",
            ["Underground"] = "Untergrund",
            ["Surface"] = "Oberfläche",
            ["Fences"] = "Zäune",
            ["Fences Style"] = "Zauntyp",
            ["Fences Color"] = "Zaunfarbe",
            ["White"] = "Weiß",
            ["Green"] = "Grün",
            ["Yellow"] = "Gelb",
            ["Slope"] = "Steigung",
            ["General Altitude"] = "Allgemeine Bauhöhe",
            ["Height"] = "Höhe",
            ["Width"] = "Breite",
            ["Leftmost Platform"] = "Linker Bahnsteig",
            ["Central Platform"] = "Mittlerere Bahnsteige",
            ["Rightmost Platform"] = "Rechter Bahnsteig",
            ["No"] = "Nein",
            ["Yes"] = "Ja",
            ["Convering Angle"] = "Winkel",
            ["Roof length"] = "Dachlänge",

            -- ["Progressive/Counter Curvature Station"] = "Progressiver/Konzentrischer Bahnhof mit Radius",
            ["Station that platform and track parameters can be fine-tuned, with two different radii at two extremities of the platforms."] = "Bahnhof mit Bahnsteig und Gleis Parametern um 2 verschiedene Radien an 2 verschiedenen Enden der Bahnsteige zu bauen.",
            ["Half-triangle Station"] = "Halb dreieckiger Bahnhof",
            ["Station that platform and track parameters can be fine-tuned, with two different radii on two sides of the station for half of the platforms, and one consistent radius for the other half."] = "Bahnhof mit Bahnsteig und Gleis Parametern um Bahnhöfe mit 2 unabhängigen Radien am einen Ende und einem festen Radius am anderen Ende zu bauen.",
            ["Triangle Station"] = "Dreieckiger Bahnhof",
            ["Station that platform and track parameters can be fine-tuned, with two different radii on two sides of the station."] = "Bahnhof mit Bahnsteig und Gleis Parametern um einen Bahnhof mit 2 unterschiedlichen Radien zu bauen.",
            ["Generic Station"] = "Generischer Bahnhof",
            ["Station that platform and track parameters can be fine-tuned, with single reference radius."] = "Bahnhof mit Bahnsteig und Gleis Parametern um Bahnhöfe mit einzelnen Radien zu bauen."
        },
        zh_CN = {
            ["name"] = "终极地下车站",
            ["desc"] = descCN,
            ["Number of tracks"] = "轨道数",
            ["Transit Tracks"] = "正线数",
            ["Position"] = "位置",
            ["Left"] = "左",
            ["Centre"] = "中",
            ["Sides"] = "两边",
            ["Right"] = "右",
            ["Radius"] = "半径",
            ["Platform"] = "站台",
            ["Length"] = "长度",
            ["Outter"] = "外侧",
            ["Polarity"] = "极性",
            ["Platform Variation"] = "站台变化",
            ["Narrowest Extremity Width"] = "收紧的站台端部",
            ["Uniform"] = "归一",
            ["Linear"] = "线性",
            ["Quadratic"] = "二次函数",
            ["Quartic"] = "四次函数",
            ["Gauusian"] = "高斯函数",
            ["Gauusian 2"] = "高斯函数2",
            ["Shortest Platform"] = "最短的站台长度",
            ["Offset Platform Max."] = "最大的站台平移",
            ["Track"] = "轨道",
            ["Reference"] = "参照物",
            ["Center"] = "中",
            ["Unaffected platforms"] = "不受变化影响的站台",
            ["Main Entry"] = "主站房",
            ["None"] = "无",
            ["Central"] = "中央",
            ["Both"] = "所有",
            ["Entry"] = "入口",
            ["Underground"] = "地道",
            ["Surface"] = "地面",
            ["Fences"] = "围栏",
            ["Fences Style"] = "围栏风格",
            ["Fences Color"] = "围栏颜色",
            ["White"] = "白色",
            ["Green"] = "绿色",
            ["Yellow"] = "黄色",
            ["Slope"] = "坡度",
            ["General Altitude"] = "整体高度",
            ["Height"] = "高度",
            ["Width"] = "宽度",
            ["Leftmost Platform"] = "左侧站台",
            ["Central Platform"] = "中央站台",
            ["Rightmost Platform"] = "右侧站台",
            ["No"] = "无",
            ["Yes"] = "有",
            ["Convering Angle"] = "夹角",
            ["Roof length"] = "雨棚长度",
            ["Central Platforms Common Block Length"] = "中央站台共享区域长度",
            ["Common Radius Part Length"] = "共半径部分长度",

            ["Progressive/Counter Curvature Station"] = "渐进曲线/反向曲线车站",
            ["Station that platform and track parameters can be fine-tuned, with two different radii at two extremities of the platforms."] 
            = "在车站前后两部分拥有不同曲率曲线的,可以进行站台参数微调的车站",
            ["Half-triangle Station"] = "半三角车站",
            ["Station that platform and track parameters can be fine-tuned, with two different radii on two sides of the station for half of the platforms, and one consistent radius for the other half."] 
            = "在车站前后两部分拥有不同曲率曲线的,其中一部分可以分为两个方向的,可以进行站台参数微调的三角形车站",
            ["Triangle Station"] = "三角车站",
            ["Station that platform and track parameters can be fine-tuned, with two different radii on two sides of the station."] 
            = "分为两个方向的,可以进行站台参数微调的三角形车站.",
            ["Generic Station"] = "普通车站",
            ["Station that platform and track parameters can be fine-tuned, with single reference radius."] 
            = "拥有一个参考曲率,可以进行站台参数微调的车站.",
            ["Terminal Station"] = "尽头式车站",
            ["Terminal Station that platform and track parameters can be fine-tuned, with single reference radius."] 
            = "拥有一个参考曲率,可以进行站台参数微调的尽头式车站.",
        }
    }
end
